"""Public package interface for IX-Autonomy-Assurance-Case-Runtime."""

from __future__ import annotations

from ix_autonomy_assurance_case_runtime._version import __version__
from ix_autonomy_assurance_case_runtime.assurance_case import (
    AssuranceCase,
    AssuranceCaseValidationReport,
    AssuranceClaim,
    AssuranceModelError,
    Assumption,
    Control,
    EvidenceLink,
    Hazard,
    Mitigation,
    VerificationCriterion,
)
from ix_autonomy_assurance_case_runtime.contracts import (
    AssuranceCaseStatus,
    AutonomyDecisionType,
    ContractDefinition,
    ContractValueError,
    EvidenceStatus,
    HazardSeverity,
    ReviewDisposition,
    RuntimeAuthorityState,
    VerificationResult,
    build_contract_catalog,
)
from ix_autonomy_assurance_case_runtime.evidence import (
    EvidenceBundle,
    EvidenceBundleValidationReport,
    EvidenceRecord,
    EvidenceRuntimeError,
    canonical_json_bytes,
    sha256_canonical_json,
    sha256_hexdigest,
)
from ix_autonomy_assurance_case_runtime.project import (
    PROJECT_NAME,
    ProjectIdentity,
    get_project_identity,
)
from ix_autonomy_assurance_case_runtime.scenarios import (
    AcceptanceCriterion,
    AutonomyFunction,
    ExpectedSafeBehavior,
    MissionThread,
    OperatingCondition,
    OperationalContext,
    Scenario,
    ScenarioCatalog,
    ScenarioCatalogValidationReport,
    ScenarioModelError,
    Stressor,
)

__all__ = [
    "PROJECT_NAME",
    "AcceptanceCriterion",
    "AssuranceCase",
    "AssuranceCaseStatus",
    "AssuranceCaseValidationReport",
    "AssuranceClaim",
    "AssuranceModelError",
    "Assumption",
    "AutonomyDecisionType",
    "AutonomyFunction",
    "ContractDefinition",
    "ContractValueError",
    "Control",
    "EvidenceBundle",
    "EvidenceBundleValidationReport",
    "EvidenceLink",
    "EvidenceRecord",
    "EvidenceRuntimeError",
    "EvidenceStatus",
    "ExpectedSafeBehavior",
    "Hazard",
    "HazardSeverity",
    "MissionThread",
    "Mitigation",
    "OperatingCondition",
    "OperationalContext",
    "ProjectIdentity",
    "ReviewDisposition",
    "RuntimeAuthorityState",
    "Scenario",
    "ScenarioCatalog",
    "ScenarioCatalogValidationReport",
    "ScenarioModelError",
    "Stressor",
    "VerificationCriterion",
    "VerificationResult",
    "__version__",
    "build_contract_catalog",
    "canonical_json_bytes",
    "get_project_identity",
    "sha256_canonical_json",
    "sha256_hexdigest",
]
